package com.example.lab7_retrofit.database.supermarket

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "supermarket_items")
data class SupermarketItemEntity(
    // id autogenerated
    @ColumnInfo(name = "id")
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    @ColumnInfo(name = "itemName")
    val name: String,

    @ColumnInfo(name = "quantity")
    val quantity: String,

    @ColumnInfo(name = "imagePath")
    val imagePath: String?
) {
    constructor(name: String, imageUrl: String, description: String?) : this(0, name, imageUrl, description)
}